//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from E:/Lukas/Projects/FirstLanguage/FirstLanguage/grammar/EduLang.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IEduLangListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class EduLangBaseListener : IEduLangListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] EduLangParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] EduLangParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] EduLangParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] EduLangParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.macro_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMacro_def([NotNull] EduLangParser.Macro_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.macro_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMacro_def([NotNull] EduLangParser.Macro_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.macro_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMacro_call([NotNull] EduLangParser.Macro_callContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.macro_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMacro_call([NotNull] EduLangParser.Macro_callContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstruction([NotNull] EduLangParser.InstructionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstruction([NotNull] EduLangParser.InstructionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.push_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPush_instr([NotNull] EduLangParser.Push_instrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.push_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPush_instr([NotNull] EduLangParser.Push_instrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.pop_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPop_instr([NotNull] EduLangParser.Pop_instrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.pop_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPop_instr([NotNull] EduLangParser.Pop_instrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.load_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoad_instr([NotNull] EduLangParser.Load_instrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.load_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoad_instr([NotNull] EduLangParser.Load_instrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.store_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStore_instr([NotNull] EduLangParser.Store_instrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.store_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStore_instr([NotNull] EduLangParser.Store_instrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.add_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdd_instr([NotNull] EduLangParser.Add_instrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.add_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdd_instr([NotNull] EduLangParser.Add_instrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.sub_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSub_instr([NotNull] EduLangParser.Sub_instrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.sub_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSub_instr([NotNull] EduLangParser.Sub_instrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.label_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLabel_instr([NotNull] EduLangParser.Label_instrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.label_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLabel_instr([NotNull] EduLangParser.Label_instrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.jumpz_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJumpz_instr([NotNull] EduLangParser.Jumpz_instrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.jumpz_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJumpz_instr([NotNull] EduLangParser.Jumpz_instrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.print_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrint_instr([NotNull] EduLangParser.Print_instrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.print_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrint_instr([NotNull] EduLangParser.Print_instrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.halt_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHalt_instr([NotNull] EduLangParser.Halt_instrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.halt_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHalt_instr([NotNull] EduLangParser.Halt_instrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.macro_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMacro_instr([NotNull] EduLangParser.Macro_instrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.macro_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMacro_instr([NotNull] EduLangParser.Macro_instrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.block_end_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock_end_instr([NotNull] EduLangParser.Block_end_instrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.block_end_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock_end_instr([NotNull] EduLangParser.Block_end_instrContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
