//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from E:/Lukas/Projects/FirstLanguage/FirstLanguage/grammar/EduLang.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="EduLangParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IEduLangVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="EduLangParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] EduLangParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EduLangParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] EduLangParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EduLangParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstruction([NotNull] EduLangParser.InstructionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EduLangParser.push_instr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPush_instr([NotNull] EduLangParser.Push_instrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EduLangParser.pop_instr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPop_instr([NotNull] EduLangParser.Pop_instrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EduLangParser.load_instr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoad_instr([NotNull] EduLangParser.Load_instrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EduLangParser.store_instr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStore_instr([NotNull] EduLangParser.Store_instrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EduLangParser.add_instr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdd_instr([NotNull] EduLangParser.Add_instrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EduLangParser.sub_instr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSub_instr([NotNull] EduLangParser.Sub_instrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EduLangParser.label_instr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabel_instr([NotNull] EduLangParser.Label_instrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EduLangParser.jumpz_instr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJumpz_instr([NotNull] EduLangParser.Jumpz_instrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EduLangParser.print_instr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrint_instr([NotNull] EduLangParser.Print_instrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EduLangParser.halt_instr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHalt_instr([NotNull] EduLangParser.Halt_instrContext context);
}
