//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from E:/Lukas/Projects/FirstLanguage/FirstLanguage/grammar/EduLang.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IEduLangListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class EduLangBaseListener : IEduLangListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] EduLangParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] EduLangParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] EduLangParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] EduLangParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstruction([NotNull] EduLangParser.InstructionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstruction([NotNull] EduLangParser.InstructionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.push_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPush_instr([NotNull] EduLangParser.Push_instrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.push_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPush_instr([NotNull] EduLangParser.Push_instrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.pop_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPop_instr([NotNull] EduLangParser.Pop_instrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.pop_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPop_instr([NotNull] EduLangParser.Pop_instrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.dup_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDup_instr([NotNull] EduLangParser.Dup_instrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.dup_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDup_instr([NotNull] EduLangParser.Dup_instrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.swap_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwap_instr([NotNull] EduLangParser.Swap_instrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.swap_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwap_instr([NotNull] EduLangParser.Swap_instrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.load_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoad_instr([NotNull] EduLangParser.Load_instrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.load_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoad_instr([NotNull] EduLangParser.Load_instrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.store_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStore_instr([NotNull] EduLangParser.Store_instrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.store_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStore_instr([NotNull] EduLangParser.Store_instrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.add_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdd_instr([NotNull] EduLangParser.Add_instrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.add_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdd_instr([NotNull] EduLangParser.Add_instrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.sub_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSub_instr([NotNull] EduLangParser.Sub_instrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.sub_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSub_instr([NotNull] EduLangParser.Sub_instrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.mul_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMul_instr([NotNull] EduLangParser.Mul_instrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.mul_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMul_instr([NotNull] EduLangParser.Mul_instrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.div_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDiv_instr([NotNull] EduLangParser.Div_instrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.div_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDiv_instr([NotNull] EduLangParser.Div_instrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.mod_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMod_instr([NotNull] EduLangParser.Mod_instrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.mod_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMod_instr([NotNull] EduLangParser.Mod_instrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.eq_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEq_instr([NotNull] EduLangParser.Eq_instrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.eq_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEq_instr([NotNull] EduLangParser.Eq_instrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.neq_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNeq_instr([NotNull] EduLangParser.Neq_instrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.neq_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNeq_instr([NotNull] EduLangParser.Neq_instrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.lt_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLt_instr([NotNull] EduLangParser.Lt_instrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.lt_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLt_instr([NotNull] EduLangParser.Lt_instrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.gt_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGt_instr([NotNull] EduLangParser.Gt_instrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.gt_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGt_instr([NotNull] EduLangParser.Gt_instrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.lte_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLte_instr([NotNull] EduLangParser.Lte_instrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.lte_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLte_instr([NotNull] EduLangParser.Lte_instrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.gte_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGte_instr([NotNull] EduLangParser.Gte_instrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.gte_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGte_instr([NotNull] EduLangParser.Gte_instrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.not_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNot_instr([NotNull] EduLangParser.Not_instrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.not_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNot_instr([NotNull] EduLangParser.Not_instrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.and_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnd_instr([NotNull] EduLangParser.And_instrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.and_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnd_instr([NotNull] EduLangParser.And_instrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.or_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOr_instr([NotNull] EduLangParser.Or_instrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.or_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOr_instr([NotNull] EduLangParser.Or_instrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.label_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLabel_instr([NotNull] EduLangParser.Label_instrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.label_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLabel_instr([NotNull] EduLangParser.Label_instrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.jump_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJump_instr([NotNull] EduLangParser.Jump_instrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.jump_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJump_instr([NotNull] EduLangParser.Jump_instrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.jumpz_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJumpz_instr([NotNull] EduLangParser.Jumpz_instrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.jumpz_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJumpz_instr([NotNull] EduLangParser.Jumpz_instrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.jumpnz_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJumpnz_instr([NotNull] EduLangParser.Jumpnz_instrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.jumpnz_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJumpnz_instr([NotNull] EduLangParser.Jumpnz_instrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.input_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInput_instr([NotNull] EduLangParser.Input_instrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.input_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInput_instr([NotNull] EduLangParser.Input_instrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.print_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrint_instr([NotNull] EduLangParser.Print_instrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.print_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrint_instr([NotNull] EduLangParser.Print_instrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.putc_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPutc_instr([NotNull] EduLangParser.Putc_instrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.putc_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPutc_instr([NotNull] EduLangParser.Putc_instrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EduLangParser.halt_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHalt_instr([NotNull] EduLangParser.Halt_instrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EduLangParser.halt_instr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHalt_instr([NotNull] EduLangParser.Halt_instrContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
